package models

type Item struct {
	Name              string `json:"name,omitempty"`
	Aura              string `json:"aura,omitempty"`
	CL                int    `json:"cl,omitempty"`
	Slot              string `json:"slot,omitempty"`
	Price             string `json:"price,omitempty"`
	Weight            string `json:"weight,omitempty"`
	Description       string `json:"description,omitempty"`
	Requirements      string `json:"requirements,omitempty"`
	Cost              string `json:"cost,omitempty"`
	Group             string `json:"group,omitempty"`
	Source            string `json:"source,omitempty"`
	AL                string `json:"al,omitempty"`
	Int               string `json:"int,omitempty"`
	Wis               string `json:"wis,omitempty"`
	Cha               string `json:"cha,omitempty"`
	Ego               string `json:"ego,omitempty"`
	Communication     string `json:"communication,omitempty"`
	Senses            string `json:"senses,omitempty"`
	Powers            string `json:"powers,omitempty"`
	MagicItems        string `json:"magicItems,omitempty"`
	FullText          string `json:"fullText,omitempty"`
	Destruction       string `json:"destruction,omitempty"`
	MinorArtifactFlag int    `json:"minorArtifactFlag,omitempty"`
	MajorArtifactFlag int    `json:"majorArtifactFlag,omitempty"`
	Abjuration        int    `json:"abjuration,omitempty"`
	Conjuration       int    `json:"conjuration,omitempty"`
	Divination        int    `json:"divination,omitempty"`
	Enchantment       int    `json:"enchantment,omitempty"`
	Evocation         int    `json:"evocation,omitempty"`
	Necromancy        int    `json:"necromancy,omitempty"`
	Transmutation     int    `json:"transmutation,omitempty"`
	AuraStrength      string `json:"auraStrength,omitempty"`
	WeightValue       int    `json:"weightValue,omitempty"`
	PriceValue        int    `json:"priceValue,omitempty"`
	CostValue         int    `json:"costValue,omitempty"`
	Languages         string `json:"languages,omitempty"`
	BaseItem          string `json:"baseItem,omitempty"`
	LinkText          string `json:"linkText,omitempty"`
	//ID                int    `json:"id,omitempty"`
	Mythic            int    `json:"mythic,omitempty"`
	LegendaryWeapon   int    `json:"legendaryWeapon,omitempty"`
	Illusion          int    `json:"illusion,omitempty"`
	Universal         int    `json:"universal,omitempty"`
	Scaling           string `json:"scaling,omitempty"`
	IsIntelligentItem int    `json:"isIntelligentItem,omitempty"`
}
