package models

type Monster struct {
	Name                  string `json:"name,omitempty"`
	CR                    string `json:"cr,omitempty"`
	XP                    int    `json:"xp,omitempty"`
	Race                  string `json:"race,omitempty"`
	Class                 string `json:"class,omitempty"`
	MonsterSource         string `json:"monsterSource,omitempty"`
	Alignment             string `json:"alignment,omitempty"`
	Size                  string `json:"size,omitempty"`
	Type                  string `json:"type,omitempty"`
	SubType               string `json:"subType,omitempty"`
	Init                  int    `json:"init,omitempty"`
	Senses                string `json:"senses,omitempty"`
	Aura                  string `json:"aura,omitempty"`
	AC                    string `json:"ac,omitempty"`
	ACMods                string `json:"ac_mods,omitempty"`
	HP                    int    `json:"hp,omitempty"`
	HD                    string `json:"hd,omitempty"`
	HPMods                string `json:"hp_mods,omitempty"`
	Saves                 string `json:"saves,omitempty"`
	Fort                  int    `json:"fort,omitempty"`
	Ref                   int    `json:"ref,omitempty"`
	Will                  int    `json:"will,omitempty"`
	SaveMods              string `json:"save_mods,omitempty"`
	DefensiveAbilities    string `json:"defensiveAbilities,omitempty"`
	DR                    string `json:"dr,omitempty"`
	Immune                string `json:"immune,omitempty"`
	Resist                string `json:"resist,omitempty"`
	SR                    string `json:"sr,omitempty"`
	Weaknesses            string `json:"weaknesses,omitempty"`
	Speed                 string `json:"speed,omitempty"`
	SpeedMod              string `json:"speed_mod,omitempty"`
	Melee                 string `json:"melee,omitempty"`
	Ranged                string `json:"ranged,omitempty"`
	Space                 string `json:"space,omitempty"`
	Reach                 string `json:"reach,omitempty"`
	SpecialAttacks        string `json:"specialAttacks,omitempty"`
	SpellLikeAbilities    string `json:"spellLikeAbilities,omitempty"`
	SpellsKnown           string `json:"spellsKnown,omitempty"`
	SpellsPrepared        string `json:"spellsPrepared,omitempty"`
	SpellDomains          string `json:"spellDomains,omitempty"`
	AbilityScores         string `json:"abilityScores,omitempty"`
	AbilityScoreMods      string `json:"abilityScore_Mods,omitempty"`
	BaseAtk               int    `json:"baseAtk,omitempty"`
	CMB                   int    `json:"cmb,omitempty"`
	CMD                   int    `json:"cmd,omitempty"`
	Feats                 string `json:"feats,omitempty"`
	Skills                string `json:"skills,omitempty"`
	RacialMods            string `json:"racialMods,omitempty"`
	Languages             string `json:"languages,omitempty"`
	SQ                    string `json:"sq,omitempty"`
	Environment           string `json:"environment,omitempty"`
	Organization          string `json:"organization,omitempty"`
	Treasure              string `json:"treasure,omitempty"`
	DescriptionVisual     string `json:"description_Visual,omitempty"`
	Group                 string `json:"group,omitempty"`
	Source                string `json:"source,omitempty"`
	IsTemplate            int    `json:"isTemplate,omitempty"`
	SpecialAbilities      string `json:"specialAbilities,omitempty"`
	Description           string `json:"description,omitempty"`
	FullText              string `json:"fullText,omitempty"`
	Gender                string `json:"gender,omitempty"`
	Bloodline             string `json:"bloodline,omitempty"`
	ProhibitedSchools     string `json:"prohibitedSchools,omitempty"`
	BeforeCombat          string `json:"beforeCombat,omitempty"`
	DuringCombat          string `json:"duringCombat,omitempty"`
	Morale                string `json:"morale,omitempty"`
	Gear                  string `json:"gear,omitempty"`
	OtherGear             string `json:"otherGear,omitempty"`
	Vulnerability         string `json:"vulnerability,omitempty"`
	Note                  string `json:"note,omitempty"`
	CharacterFlag         int    `json:"characterFlag,omitempty"`
	CompanionFlag         int    `json:"companionFlag,omitempty"`
	Fly                   int    `json:"fly,omitempty"`
	Climb                 int    `json:"climb,omitempty"`
	Burrow                int    `json:"burrow,omitempty"`
	Swim                  int    `json:"swim,omitempty"`
	Land                  int    `json:"land,omitempty"`
	TemplatesApplied      string `json:"templatesApplied,omitempty"`
	OffenseNote           string `json:"offenseNote,omitempty"`
	BaseStatistics        string `json:"baseStatistics,omitempty"`
	ExtractsPrepared      string `json:"extractsPrepared,omitempty"`
	AgeCategory           string `json:"ageCategory,omitempty"`
	DontUseRacialHD       int    `json:"dontUseRacialHD,omitempty"`
	VariantParent         string `json:"variantParent,omitempty"`
	Mystery               string `json:"mystery,omitempty"`
	ClassArchetypes       string `json:"classArchetypes,omitempty"`
	Patron                string `json:"patron,omitempty"`
	CompanionFamiliarLink string `json:"companionFamiliarLink,omitempty"`
	FocusedSchool         string `json:"focusedSchool,omitempty"`
	Traits                string `json:"traits,omitempty"`
	AlternateNameForm     string `json:"alternateNameForm,omitempty"`
	StatisticsNote        string `json:"statisticsNote,omitempty"`
	LinkText              string `json:"linkText,omitempty"`
	//ID                    int    `json:"id,omitempty"`
	UniqueMonster         int    `json:"uniqueMonster,omitempty"`
	MR                    int    `json:"mr,omitempty"`
	Mythic                int    `json:"mythic,omitempty"`
	MT                    int    `json:"mt,omitempty"`
}
