export interface Spell {
    name                : string
    school              : string
    subschool           : string
    descriptor          : string
    spell_level          : string
    castingTime         : string
    components          : string
    costlyComponents    : number
    range               : string
    area                : string
    effect              : string
    targets             : string
    duration            : string
    dismissible         : number
    shapeable           : number
    savingThrow         : string
    spellResistance     : string
    description         : string
    descriptionFormatted: string
    source              : string
    fullText            : string
    verbal              : number
    somatic             : number
    material            : number
    focus               : number
    divineFocus         : number
    sor                 : number
    wiz                 : number
    cleric              : string
    druid               : string
    ranger              : string
    bard                : string
    paladin             : string
    alchemist           : string
    summoner            : string
    witch               : string
    inquisitor          : string
    oracle              : string
    antipaladin         : string
    magus               : number
    adept               : string
    deity               : string
    SLA_Level            : number// spell like ability level
    domain              : string
    short_description    : string
    acid                : number
    air                 : number
    chaotic             : number
    cold                : number
    curse               : number
    darkness            : number
    death               : number
    disease             : number
    earth               : number
    electricity         : number
    emotion             : number
    evil                : number
    fear                : number
    fire                : number
    force               : number
    good                : number
    languageDependent   : number
    lawful              : number
    light               : number
    mindAffecting       : number
    pain                : number
    poison              : number
    shadow              : number
    sonic               : number
    water               : number
    linktext            : string
    iD                  : number
    materialCosts       : string
    bloodline           : string
    patron              : string
    mythicText          : string
    augmented           : string
    mythic              : number
    bloodrager          : number
    shaman              : string
    psychic             : string
    medium              : string
    mesmerist           : string
    occultist           : string
    spiritualist        : string
    skald               : string
    investigator        : string
    hunter              : string
    hauntStatistics     : string
    ruse                : number
    draconic            : number
    meditative          : number
    summonerUnchained   : string
}
